searches = [  
    # Each search will generate a maximum of 100 titles for model to be trained on
    'Cyberpunk 2077',
    'Samuri Build',
    'What 1000 hours of Cyberpunk looks like',
    'Cyberpunk 2.0',
    'Sandevstian Build',
    'Gorilla Arms Cyberpunk',
    'Cyberpunk letsplay',
    'Cyberpunk mission ',
    'Cyberpunk netrunner build',
    'Cyberpunk Johnny',
    'Cyberpunk best weapons',
    'Cyberpunk Katana',
    'Cyberpunk update',
    'Cyberpunk builds',
    'Iconic Cyberware',
    'Cyberpunk wakako',
    'Cyberpunk gigs',
    'Cyberpunk adam smasher',
    'Boss fight cyberpunk',
    'Cyberpunk gameplay',
    'Cyberpunk',
    'Aggressive Gameplay Cyberpunk',
    'Katana build cyberpunk',
    'Meet hanako at embers',
    'Cyberpunk maxtac',
    'Cyberpunk lore',
]