searches = [  
    # Each search will generate a maximum of 100 titles for model to be trained on
    'Cyberpunk 2077',
    'Samuri Build',
    'What 1000 hours of Cyberpunk looks like',
    'Cyberpunk 2.0',
    'Sandevstian Build',
    'Gorilla Arms Cyberpunk',
    'Cyberpunk letsplay',
    'Cyberpunk mission ',
    'Cyberpunk netrunner build',
    'Cyberpunk Johnny',
    'Cyberpunk best weapons',
    'Cyberpunk Katana',
    'Cyberpunk update',
    'Cyberpunk builds',
    'Iconic Cyberware',
    'Cyberpunk wakako',
    'Cyberpunk gigs',
    'Cyberpunk adam smasher',
    'Boss fight cyberpunk',
    'Cyberpunk gameplay',
    'Cyberpunk',
    'Aggressive Gameplay Cyberpunk',
    'Katana build cyberpunk',
    'Meet hanako at embers',
    'Cyberpunk maxtac',
    'Cyberpunk lore',
    'Cyberpunk net samurai'
    'Cyberpunk dakota'
]

categories = [
    'Cyberpunk sentence: ',
    'Samurai Build sentence:',
    'Cyberpunk sentence: ',
    'Cyberpunk sentence: ',
    'Sandevstian sentence: ',
    'Gorilla Arms sentence:',
    'letsplay sentence: ',
    'mission sentence: ',
    'netrunner sentence: ',
    'Johnny sentence: ',
    'best weapons sentence: ',
    'Katana sentence',
    'Cyberpunk sentence: ',
    'builds sentence: ',
    'Iconic Cyberware sentence: ',
    'wakako sentence: ',
    'gigs sentence: ',
    'adam smasher sentence: ',
    'Boss sentence: ',
    'gameplay sentence: ',
    'Cyberpunk sentence: ',
    'Aggressive Gameplay sentence: ',
    'Katana build sentence: ',
    'Meet hanako at embers sentence: ',
    'maxtac sentence: ',
    'lore sentence: ',
    'net samurai sentence: '
    'dakota sentence: '
]